---
# tasks file for change_documentroot
- name: "Install httpd package"
  package:
          name: httpd
          state: present
- name: "customize document root httpd "
  file:
          state: directory
          path: "/var/www/mydocumentroot"
- name: "copy index page"
  copy:
        src: "index.html"
        dest: "/var/www/mydocumentroot/index.html"
- name: "copy documentroot config file"
  template:
        src: "custom_document_root.conf"
        dest: "/etc/httpd/conf/"
  notify:
          - Restart_httpd
- name: "start the httpd service"
  service:
        name: httpd
        state: started

- name: "Enable 88 port through firewall"
  firewalld:
        port: 88/tcp
        state: enabled
        permanent: yes
        immediate: yes
- name: "check the status of httpd service"
  shell:
        cmd: systemctl status httpd
  register: status
- name: "show output"
  debug:
        var: status


